USE imo_system;

DROP TABLE IF EXISTS produtos;

CREATE TABLE produtos (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    tamanho VARCHAR(10) NOT NULL,
    peso DECIMAL(5,2) UNSIGNED NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    cor VARCHAR(30),
    preco_venda DECIMAL(5,2) UNSIGNED NOT NULL,
    preco_custo DECIMAL(5,2) UNSIGNED NOT NULL,
    stock SMALLINT UNSIGNED NOT NULL
);